const MENU_DATA = {
  meals: [
    { id: 'm1', name: 'Carne Asada Tacos', price: 12.50, desc: 'Three soft corn tortillas filled with grilled steak, onions, cilantro, and lime.', emoji: '🌮', badge: 'popular', cal: 520, time: '12 min' },
    { id: 'm2', name: 'Al Pastor Tacos', price: 13.00, desc: 'Marinated pork with pineapple, onion, and cilantro on corn tortillas.', emoji: '🌮', badge: 'popular', cal: 480, time: '12 min' },
    { id: 'm3', name: 'Baja Fish Tacos', price: 14.50, desc: 'Crispy battered fish topped with cabbage slaw, crema, and salsa verde.', emoji: '🐟', badge: 'new', cal: 440, time: '14 min' },
    { id: 'm4', name: 'Shrimp Lettuce Tacos', price: 15.50, desc: 'Citrus shrimp served in lettuce cups with mango salsa and cucumber slaw.', emoji: '🦐', badge: '', cal: 320, time: '10 min' },
    { id: 'm5', name: 'Grilled Veggie Tacos', price: 12.00, desc: 'Corn tortillas filled with grilled seasonal veggies, black beans, and avocado.', emoji: '🥬', badge: '', cal: 380, time: '10 min' },
    { id: 'm6', name: 'Chicken Tinga Tacos', price: 11.50, desc: 'Shredded chicken simmered in a chipotle-tomato sauce, topped with crema.', emoji: '🍗', badge: '', cal: 460, time: '12 min' },
    { id: 'm7', name: 'Carnitas Classic', price: 13.50, desc: 'Slow-braised pulled pork with cilantro, onion, and salsa verde on corn tortillas.', emoji: '🥩', badge: 'popular', cal: 510, time: '14 min' },
    { id: 'm8', name: 'Barbacoa Tacos', price: 14.00, desc: 'Tender shredded beef with traditional spices, served with consomé on the side.', emoji: '🌮', badge: '', cal: 540, time: '15 min' },
    { id: 'm9', name: 'Pollo Asado Tacos', price: 12.00, desc: 'Grilled marinated chicken with roasted corn salsa and chipotle crema.', emoji: '🌮', badge: '', cal: 420, time: '12 min' },
    { id: 'm10', name: 'Mushroom Tacos', price: 11.00, desc: 'Sauteed wild mushrooms with epazote, Oaxaca cheese, and salsa negra.', emoji: '🍄', badge: 'new', cal: 340, time: '10 min' },
  ],
  drinks: [
    { id: 'd1', name: 'Classic Margarita', price: 10.00, desc: 'House silver tequila, fresh lime juice, and agave nectar with a salt rim.', emoji: '🍹', badge: 'popular', cal: 210, time: '3 min' },
    { id: 'd2', name: 'Spicy Jalapeño Marg', price: 11.00, desc: 'Our classic margarita infused with fresh jalapeños and a chili-salt rim.', emoji: '🌶️', badge: '', cal: 220, time: '3 min' },
    { id: 'd3', name: 'Paloma', price: 10.50, desc: 'Tequila, grapefruit soda, and fresh lime juice served tall over ice.', emoji: '🍹', badge: '', cal: 180, time: '3 min' },
    { id: 'd4', name: 'Michelada', price: 9.00, desc: 'Mexican lager with tomato juice, lime, spices, and a chili rim.', emoji: '🍺', badge: '', cal: 160, time: '3 min' },
    { id: 'd5', name: 'House Horchata', price: 4.50, desc: 'Traditional rice milk beverage flavored with cinnamon and vanilla.', emoji: '🥛', badge: 'popular', cal: 180, time: '1 min' },
    { id: 'd6', name: 'Agua Fresca', price: 4.00, desc: 'Refreshing seasonal fruit water — ask about today\'s flavors.', emoji: '🥤', badge: '', cal: 120, time: '1 min' },
    { id: 'd7', name: 'Mexican Coke', price: 3.50, desc: 'Coca-Cola made with real cane sugar, imported from Mexico in a glass bottle.', emoji: '🍶', badge: '', cal: 150, time: '1 min' },
    { id: 'd8', name: 'Tamarind Soda', price: 4.00, desc: 'Sweet and tangy tamarind-flavored Mexican soft drink.', emoji: '🥤', badge: 'new', cal: 160, time: '1 min' },
    { id: 'd9', name: 'Jarritos Lime', price: 3.50, desc: 'Popular Mexican lime soda, crisp and refreshing.', emoji: '🍋', badge: '', cal: 140, time: '1 min' },
    { id: 'd10', name: 'Iced Mexican Coffee', price: 5.00, desc: 'Cold brew coffee with cinnamon, vanilla, and a touch of condensed milk.', emoji: '☕', badge: 'new', cal: 110, time: '2 min' },
  ],
  sides: [
    { id: 's1', name: 'Chips & Salsa', price: 4.00, desc: 'House-made tortilla chips served with our signature roasted tomato salsa.', emoji: '🫓', badge: 'popular', cal: 320, time: '2 min' },
    { id: 's2', name: 'Guacamole & Chips', price: 9.00, desc: 'Freshly mashed avocados with tomato, onion, cilantro, and jalapeño.', emoji: '🥑', badge: 'popular', cal: 440, time: '3 min' },
    { id: 's3', name: 'Queso Blanco', price: 7.50, desc: 'Creamy white cheese dip with diced mild green chiles and spices.', emoji: '🧀', badge: '', cal: 380, time: '3 min' },
    { id: 's4', name: 'Trio Dip Sampler', price: 11.00, desc: 'A flight of our salsa, guacamole, and queso blanco served with extra chips.', emoji: '🍽️', badge: 'popular', cal: 620, time: '4 min' },
    { id: 's5', name: 'Mexican Street Corn', price: 5.50, desc: 'Grilled elote with mayo, cotija cheese, chili powder, and lime.', emoji: '🌽', badge: 'new', cal: 280, time: '5 min' },
    { id: 's6', name: 'Refried Beans', price: 3.50, desc: 'Creamy traditional refried pinto beans topped with queso fresco.', emoji: '🫘', badge: '', cal: 220, time: '2 min' },
    { id: 's7', name: 'Mexican Rice', price: 3.50, desc: 'Seasoned tomato rice with peas, carrots, and a blend of Mexican spices.', emoji: '🍚', badge: '', cal: 240, time: '2 min' },
    { id: 's8', name: 'Jalapeño Poppers', price: 6.50, desc: 'Stuffed jalapeños with cream cheese, wrapped in bacon and fried golden.', emoji: '🌶️', badge: '', cal: 360, time: '5 min' },
    { id: 's9', name: 'Elote Fries', price: 7.00, desc: 'Crispy fries topped with mayo, cotija, chili-lime seasoning, and cilantro.', emoji: '🍟', badge: 'new', cal: 410, time: '6 min' },
    { id: 's10', name: 'Quesadilla Bites', price: 5.00, desc: 'Crispy flour tortilla bites filled with melted cheese and served with salsa.', emoji: '🧀', badge: '', cal: 300, time: '4 min' },
  ],
  burgers: [
    { id: 'b1', name: 'Classic Mexi Burger', price: 13.50, desc: 'Grilled beef patty, pepper jack, lettuce, tomato, chipotle mayo on a brioche bun.', emoji: '🍔', badge: 'popular', cal: 680, time: '12 min' },
    { id: 'b2', name: 'Chipotle Bacon Burger', price: 15.00, desc: 'Double smoked bacon, chipotle aioli, caramelized onions, pepper jack cheese.', emoji: '🥓', badge: '', cal: 780, time: '14 min' },
    { id: 'b3', name: 'Avocado Ranch Burger', price: 14.50, desc: 'Fresh avocado, ranch dressing, crispy onion rings, and cheddar on a toasted bun.', emoji: '🥑', badge: 'new', cal: 720, time: '13 min' },
    { id: 'b4', name: 'Spicy Jalapeño Burger', price: 14.00, desc: 'Jalapeño cream cheese, pickled jalapeños, habanero sauce, pepper jack.', emoji: '🌶️', badge: '', cal: 740, time: '12 min' },
    { id: 'b5', name: 'Mushroom Swiss Burger', price: 14.50, desc: 'Sautéed mushrooms, Swiss cheese, truffle aioli, arugula on a pretzel bun.', emoji: '🍄', badge: '', cal: 690, time: '13 min' },
    { id: 'b6', name: 'BBQ Fiesta Burger', price: 15.50, desc: 'Smoky BBQ sauce, crispy onions, bacon, jalapeños, and smoked gouda.', emoji: '🔥', badge: 'popular', cal: 810, time: '14 min' },
    { id: 'b7', name: 'Veggie Fiesta Burger', price: 12.50, desc: 'House-made black bean patty, avocado, lettuce, tomato, cilantro-lime mayo.', emoji: '🌱', badge: '', cal: 480, time: '10 min' },
    { id: 'b8', name: 'Carne Asada Burger', price: 16.00, desc: 'Grilled marinated steak, queso Oaxaca, roasted peppers, chimichurri.', emoji: '🥩', badge: 'new', cal: 760, time: '15 min' },
    { id: 'b9', name: 'Double Smash Burger', price: 17.00, desc: 'Two smashed patties, American cheese, pickles, onions, special sauce.', emoji: '🍔', badge: '', cal: 920, time: '14 min' },
    { id: 'b10', name: 'Crispy Chicken Burger', price: 13.00, desc: 'Buttermilk fried chicken, coleslaw, pickles, hot honey on a brioche bun.', emoji: '🍗', badge: '', cal: 640, time: '12 min' },
  ],
  cakes: [
    { id: 'c1', name: 'Tres Leches Cake', price: 7.50, desc: 'Classic sponge cake soaked in three milks, topped with whipped cream and cinnamon.', emoji: '🍰', badge: 'popular', cal: 380, time: '2 min' },
    { id: 'c2', name: 'Churro Bites', price: 6.00, desc: 'Crispy cinnamon-sugar churro bites with chocolate and caramel dipping sauces.', emoji: '🍩', badge: 'popular', cal: 420, time: '3 min' },
    { id: 'c3', name: 'Chocolate Flan', price: 7.00, desc: 'Creamy vanilla custard with a rich caramel layer and chocolate drizzle.', emoji: '🍮', badge: '', cal: 340, time: '2 min' },
    { id: 'c4', name: 'Sopapilla Cheesecake', price: 8.00, desc: 'Flaky pastry cheesecake with honey drizzle and cinnamon sugar.', emoji: '🥧', badge: 'new', cal: 460, time: '3 min' },
    { id: 'c5', name: 'Coconut Tres Leches', price: 8.50, desc: 'Tres leches with coconut milk, topped with toasted coconut flakes.', emoji: '🥥', badge: '', cal: 400, time: '2 min' },
    { id: 'c6', name: 'Chocolate Lava Cake', price: 9.00, desc: 'Warm chocolate cake with a molten center, served with vanilla ice cream.', emoji: '🍫', badge: 'popular', cal: 520, time: '8 min' },
    { id: 'c7', name: 'Key Lime Pie', price: 7.00, desc: 'Tangy key lime custard in a graham cracker crust with whipped cream.', emoji: '🥧', badge: '', cal: 360, time: '2 min' },
    { id: 'c8', name: 'Horchata Ice Cream', price: 5.50, desc: 'Creamy horchata-flavored ice cream with cinnamon and a caramel swirl.', emoji: '🍦', badge: '', cal: 280, time: '1 min' },
    { id: 'c9', name: 'Dulce de Leche Brownie', price: 7.50, desc: 'Fudgy chocolate brownie topped with dulce de leche and sea salt.', emoji: '🍫', badge: 'new', cal: 480, time: '2 min' },
    { id: 'c10', name: 'Mango Paleta', price: 4.50, desc: 'Refreshing mango popsicle made with real Mexican mango and chili-lime.', emoji: '🍦', badge: '', cal: 120, time: '1 min' },
  ],
  fruits: [
    { id: 'f1', name: 'Mango con Chili', price: 5.50, desc: 'Fresh sliced mango with Tajín chili-lime seasoning and chamoy drizzle.', emoji: '🥭', badge: 'popular', cal: 160, time: '2 min' },
    { id: 'f2', name: 'Pineapple & Chamoy', price: 5.00, desc: 'Fresh pineapple chunks with chamoy, lime, and a sprinkle of Tajín.', emoji: '🍍', badge: '', cal: 140, time: '2 min' },
    { id: 'f3', name: 'Watermelon Agua Fresca Cup', price: 4.50, desc: 'Fresh watermelon chunks infused with lime and a hint of mint.', emoji: '🍉', badge: '', cal: 100, time: '2 min' },
    { id: 'f4', name: 'Papaya & Lime', price: 5.00, desc: 'Ripe papaya with fresh lime juice and a pinch of chili powder.', emoji: '🍈', badge: '', cal: 120, time: '2 min' },
    { id: 'f5', name: 'Mixed Fruit Cup', price: 6.00, desc: 'Seasonal mix of mango, pineapple, watermelon, and jicama with Tajín.', emoji: '🥗', badge: 'popular', cal: 150, time: '3 min' },
    { id: 'f6', name: 'Coconut Fruit Bowl', price: 7.00, desc: 'Fresh tropical fruits served in a coconut shell with lime and chili.', emoji: '🥥', badge: 'new', cal: 180, time: '3 min' },
    { id: 'f7', name: 'Grapefruit Paloma Cup', price: 5.50, desc: 'Fresh grapefruit segments with salt, lime, and a splash of grapefruit soda.', emoji: '🍊', badge: '', cal: 110, time: '2 min' },
    { id: 'f8', name: 'Cucumber & Lime Cup', price: 4.50, desc: 'Crisp cucumber slices with lime juice, salt, and chamoy.', emoji: '🥒', badge: '', cal: 60, time: '2 min' },
    { id: 'f9', name: 'Tropical Smoothie Bowl', price: 8.00, desc: 'Blended mango, pineapple, and banana topped with granola, coconut, and chia.', emoji: '🥣', badge: 'new', cal: 280, time: '4 min' },
    { id: 'f10', name: 'Elote Fruit Cup', price: 6.50, desc: 'Grilled corn kernels with mayo, cotija, chili-lime seasoning, and lime.', emoji: '🌽', badge: '', cal: 220, time: '3 min' },
  ]
};
